### ISSUE TITLE
Doesn't work with Babel 6

### ISSUE THREAD

**Issue by tomaash** [mweststrate/mobx-react-boilerplate#2]
After updating this boilerplate to Babel 6, react component stopped updating. When I enable log, I get the mobservable updates, but the render function does not run anymore. And no errors in console. If you are able to update this boilerplate to Babel 6 and don't encounter the issue, it is as good as closed :)

**Comment by mweststrate** [comment]
Seems that babel6 does not support decorators yet, so I would recommend sticking to babel5 until they do add it.

```
Module build failed: SyntaxError: /home/michel/mobservable/mobservable-react-boilerplate/src/index.js: Decorators are not supported yet in 6.x pending proposal update.
```

**Comment by tomaash** [comment]
Ah, now I feel stupid that I didn't spot that. For some reason, in my setup it failed silently. I'll see if I can fix it with https://www.npmjs.com/package/babel-plugin-transform-decorators. Thanks!

**Comment by mweststrate** [comment]
I now upgraded the repo to Babel 6 and MobX 2
